name: Continuos Integration

on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: run install, build, lint and test
        run: |
          npm install
          npm run lint
          npm run build 
          npm run test

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress Test
        uses: cypress-io/github-action@6
        with:
          build: npm run build
          start: npm run start

