name: Continuos Integration

on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: run install, build, lint and test
        run: |
          npm install
          npm run lint
          npm run build

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true